### ISSUE TITLE
Unexpected error fetching opennem data: 'fuel_tech'

### ISSUE THREAD

**Issue by ffrog8** [bacco007/sensor.opennem#20]
Hi looks like a change may have occurred with open nem api?

## Version of the custom_component

Latest
## Log

```yaml

{
  "home_assistant": {
    "installation_type": "Home Assistant Container",
    "version": "2022.9.0",
    "dev": false,
    "hassio": false,
    "virtualenv": false,
    "python_version": "3.10.5",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Australia/Adelaide",
    "os_name": "Linux",
    "os_version": "4.4.59+",
    "run_as_root": true
  },

    "device": {
      "name": "OpenNEM SA",
      "name_by_user": null,
      "model": "SA",
      "manufacturer": "OpenNEM",
      "sw_version": null,
      "disabled": false,
      "disabled_by": null,
      "entities": {
        "sensor.opennem_sa": {
          "name": null,
          "original_name": "OpenNEM SA",
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": "connectivity",
          "icon": null,
          "original_icon": "mdi:transmission-tower",
          "unit_of_measurement": "MW",
          "state": {
            "state": "unavailable",
            "attributes": {
              "unit_of_measurement": "MW",
              "device_class": "connectivity",
              "icon": "mdi:transmission-tower",
              "friendly_name": "OpenNEM SA"
            },
            "last_changed": "2022-10-19T10:35:03.055134+00:00",
            "last_updated": "2022-10-19T10:35:03.055134+00:00"
          }
        }
      }
    }
  }
}
```

## Debug log

```text


Source: custom_components/opennem/__init__.py:262
Integration: OpenNEM ([documentation](https://github.com/bacco007/sensor.opennem), [issues](https://github.com/bacco007/sensor.opennem/issues))
First occurred: 4:33:45 PM (28 occurrences)
Last logged: 8:55:00 PM

Unexpected error fetching opennem data: 'fuel_tech'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/opennem/__init__.py", line 262, in async_update
    ftype = row["fuel_tech"]
KeyError: 'fuel_tech'
```

## Describe the bug

open nem reported as unavailable

**Comment by bacco007** [comment]
Latest version should resolve this issue, thanks for reporting it

**Comment by ffrog8** [comment]
Confirmed its fixed! Cheers
