### ISSUE TITLE
Breaking Change with Home Assistant 2023.8.beta

### ISSUE THREAD

**Issue by purcell-lab** [bacco007/sensor.opennem#24]
## Version of the custom_component

OpenNEM: Version 2023.02.1 is starting

## Configuration

![image](https://github.com/bacco007/sensor.opennem/assets/79175134/92f9a517-fd71-4902-8d29-b993636a99bd)

## Describe the bug

With the upload of Home Assistant 2023.8.beta it would appear that OpenNem custom integration is no longer functional as entites are no longer loaded:

![image](https://github.com/bacco007/sensor.opennem/assets/79175134/850cabf9-6da5-4e0d-9b33-93f93e0e5c97)

## Debug log

```text
2023-07-29 17:36:26.455 DEBUG (MainThread) [custom_components.opennem] OpenNEM: Removed Config for a7ee906f3b8d7aec3092671872d4b716
2023-07-29 17:36:26.455 INFO (MainThread) [custom_components.opennem] OpenNEM: Version 2023.02.1 is starting
2023-07-29 17:36:26.456 DEBUG (MainThread) [custom_components.opennem] OpenNEM [au1]: Data will be updated every 0:10:00
2023-07-29 17:36:26.457 DEBUG (MainThread) [custom_components.opennem] OpenNEM [au]: Default Values - {'bioenergy_biomass': 0, 'bioenergy_biogas': 0, 'coal_black': 0, 'coal_brown': 0, 'distillate': 0, 'gas_ccgt': 0, 'gas_ocgt': 0, 'gas_recip': 0, 'gas_steam': 0, 'gas_wcmg': 0, 'hydro': 0, 'pumps': 0, 'solar_utility': 0, 'solar_rooftop': 0, 'wind': 0, 'battery_discharging': 0, 'battery_charging': 0, 'exports': 0, 'imports': 0, 'price': 0, 'demand': 0, 'generation': 0, 'temperature': 0, 'fossilfuel': 0, 'renewables': 0, 'flow_NSW': 0, 'flow_QLD': 0, 'flow_SA': 0, 'flow_TAS': 0, 'flow_VIC': 0, 'last_update': None}
2023-07-29 17:36:26.763 DEBUG (MainThread) [custom_components.opennem] OpenNEM [au1]: Getting State from https://data.opennem.org.au/v3/stats/au/AU/power/7d.json
2023-07-29 17:36:27.090 DEBUG (MainThread) [custom_components.opennem] OpenNEM [au1]: Getting Flow State from https://api.opennem.org.au/stats/flow/network/NEM
2023-07-29 17:36:27.124 DEBUG (MainThread) [custom_components.opennem] OpenNEM [au1]: Data Downloaded, Commencing Processing
2023-07-29 17:36:27.125 DEBUG (MainThread) [custom_components.opennem] OpenNEM [au1]: Values Before - {'bioenergy_biomass': 0, 'bioenergy_biogas': 0, 'coal_black': 0, 'coal_brown': 0, 'distillate': 0, 'gas_ccgt': 0, 'gas_ocgt': 0, 'gas_recip': 0, 'gas_steam': 0, 'gas_wcmg': 0, 'hydro': 0, 'pumps': 0, 'solar_utility': 0, 'solar_rooftop': 0, 'wind': 0, 'battery_discharging': 0, 'battery_charging': 0, 'exports': 0, 'imports': 0, 'price': 0, 'demand': 0, 'generation': 0, 'temperature': 0, 'fossilfuel': 0, 'renewables': 0, 'flow_NSW': 0, 'flow_QLD': 0, 'flow_SA': 0, 'flow_TAS': 0, 'flow_VIC': 0, 'last_update': None}
2023-07-29 17:36:27.125 DEBUG (MainThread) [custom_components.opennem] OpenNEM [au1]: Values After - {'bioenergy_biomass': 11.7, 'bioenergy_biogas': 11.1, 'coal_black': 10911.0, 'coal_brown': 4302.0, 'distillate': -0.1, 'gas_ccgt': 1493.0, 'gas_ocgt': 109.0, 'gas_recip': 0.0, 'gas_steam': 61.0, 'gas_wcmg': 56.31, 'hydro': 2967.0, 'pumps': 382.8, 'solar_utility': 195.6, 'solar_rooftop': 2151.0, 'wind': 3766.0, 'battery_discharging': 84.73, 'battery_charging': -0.48, 'exports': 0, 'imports': 0, 'price': 124.7, 'demand': 8621.0, 'generation': 26034.61, 'temperature': 0, 'fossilfuel': 16932.21, 'renewables': 9102.4, 'flow_NSW': 0, 'flow_QLD': 0, 'flow_SA': 0, 'flow_TAS': 0, 'flow_VIC': 0, 'last_update': datetime.datetime(2023, 7, 29, 7, 35, 39, tzinfo=datetime.timezone.utc), 'state': 26034.61, 'genvsdemand': 17413.61}
2023-07-29 17:36:27.125 DEBUG (MainThread) [custom_components.opennem] OpenNEM [au1] Region Attrs: ['demand', 'battery_charging', 'battery_discharging', 'bioenergy_biogas', 'bioenergy_biomass', 'coal_black', 'coal_brown', 'distillate', 'gas_ccgt', 'gas_ocgt', 'gas_recip', 'gas_steam', 'gas_wcmg', 'hydro', 'pumps', 'solar_rooftop', 'solar_utility', 'wind', 'price', 'fossilfuel', 'renewables', 'generation', 'genvsdemand', 'last_update']
2023-07-29 17:36:27.125 DEBUG (MainThread) [custom_components.opennem] OpenNEM [au1]: Values to pass to Sensor: {'bioenergy_biomass': 11.7, 'bioenergy_biogas': 11.1, 'coal_black': 10911.0, 'coal_brown': 4302.0, 'distillate': -0.1, 'gas_ccgt': 1493.0, 'gas_ocgt': 109.0, 'gas_recip': 0.0, 'gas_steam': 61.0, 'gas_wcmg': 56.31, 'hydro': 2967.0, 'pumps': 382.8, 'solar_utility': 195.6, 'solar_rooftop': 2151.0, 'wind': 3766.0, 'battery_discharging': 84.73, 'battery_charging': -0.48, 'price': 124.7, 'demand': 8621.0, 'generation': 26034.61, 'fossilfuel': 16932.21, 'renewables': 9102.4, 'last_update': datetime.datetime(2023, 7, 29, 7, 35, 39, tzinfo=datetime.timezone.utc), 'genvsdemand': 17413.61}
2023-07-29 17:36:27.125 DEBUG (MainThread) [custom_components.opennem] OpenNEM [au1]: Temp - {'bioenergy_biomass': 0, 'bioenergy_biogas': 0, 'coal_black': 0, 'coal_brown': 0, 'distillate': 0, 'gas_ccgt': 0, 'gas_ocgt': 0, 'gas_recip': 0, 'gas_steam': 0, 'gas_wcmg': 0, 'hydro': 0, 'pumps': 0, 'solar_utility': 0, 'solar_rooftop': 0, 'wind': 0, 'battery_discharging': 0, 'battery_charging': 0, 'exports': 0, 'imports': 0, 'price': 0, 'demand': 0, 'generation': 0, 'temperature': 0, 'fossilfuel': 0, 'renewables': 0, 'flow_NSW': 0, 'flow_QLD': 0, 'flow_SA': 0, 'flow_TAS': 0, 'flow_VIC': 0, 'last_update': None}
2023-07-29 17:36:27.126 DEBUG (MainThread) [custom_components.opennem] OpenNEM [au1]: Values After - {'bioenergy_biomass': 0, 'bioenergy_biogas': 0, 'coal_black': 0, 'coal_brown': 0, 'distillate': 0, 'gas_ccgt': 0, 'gas_ocgt': 0, 'gas_recip': 0, 'gas_steam': 0, 'gas_wcmg': 0, 'hydro': 0, 'pumps': 0, 'solar_utility': 0, 'solar_rooftop': 0, 'wind': 0, 'battery_discharging': 0, 'battery_charging': 0, 'exports': 0, 'imports': 0, 'price': 0, 'demand': 0, 'generation': 0, 'temperature': 0, 'fossilfuel': 0, 'renewables': 0, 'flow_NSW': 0, 'flow_QLD': 0, 'flow_SA': 0, 'flow_TAS': 0, 'flow_VIC': 0, 'last_update': None}
2023-07-29 17:36:27.127 DEBUG (MainThread) [custom_components.opennem] Finished fetching opennem data in 0.671 seconds (success: True)
2023-07-29 17:36:27.128 DEBUG (MainThread) [custom_components.opennem.sensor] OpenNEM: Sensor Setup Complete
2023-07-29 17:36:27.129 DEBUG (MainThread) [custom_components.opennem] OpenNEM [au]: Default Values - {'bioenergy_biomass': 0, 'bioenergy_biogas': 0, 'coal_black': 0, 'coal_brown': 0, 'distillate': 0, 'gas_ccgt': 0, 'gas_ocgt': 0, 'gas_recip': 0, 'gas_steam': 0, 'gas_wcmg': 0, 'hydro': 0, 'pumps': 0, 'solar_utility': 0, 'solar_rooftop': 0, 'wind': 0, 'battery_discharging': 0, 'battery_charging': 0, 'exports': 0, 'imports': 0, 'price': 0, 'demand': 0, 'generation': 0, 'temperature': 0, 'fossilfuel': 0, 'renewables': 0, 'flow_NSW': 0, 'flow_QLD': 0, 'flow_SA': 0, 'flow_TAS': 0, 'flow_VIC': 0, 'last_update': None}
2023-07-29 17:36:27.210 DEBUG (MainThread) [custom_components.opennem] OpenNEM [au1]: Getting State from https://data.opennem.org.au/v3/stats/au/AU/power/7d.json
2023-07-29 17:36:27.485 DEBUG (MainThread) [custom_components.opennem] OpenNEM [au1]: Getting Flow State from https://api.opennem.org.au/stats/flow/network/NEM
2023-07-29 17:36:27.520 DEBUG (MainThread) [custom_components.opennem] OpenNEM [au1]: Data Downloaded, Commencing Processing
2023-07-29 17:36:27.520 DEBUG (MainThread) [custom_components.opennem] OpenNEM [au1]: Values Before - {'bioenergy_biomass': 0, 'bioenergy_biogas': 0, 'coal_black': 0, 'coal_brown': 0, 'distillate': 0, 'gas_ccgt': 0, 'gas_ocgt': 0, 'gas_recip': 0, 'gas_steam': 0, 'gas_wcmg': 0, 'hydro': 0, 'pumps': 0, 'solar_utility': 0, 'solar_rooftop': 0, 'wind': 0, 'battery_discharging': 0, 'battery_charging': 0, 'exports': 0, 'imports': 0, 'price': 0, 'demand': 0, 'generation': 0, 'temperature': 0, 'fossilfuel': 0, 'renewables': 0, 'flow_NSW': 0, 'flow_QLD': 0, 'flow_SA': 0, 'flow_TAS': 0, 'flow_VIC': 0, 'last_update': None}
2023-07-29 17:36:27.521 DEBUG (MainThread) [custom_components.opennem] OpenNEM [au1]: Values After - {'bioenergy_biomass': 11.7, 'bioenergy_biogas': 11.1, 'coal_black': 10911.0, 'coal_brown': 4302.0, 'distillate': -0.1, 'gas_ccgt': 1493.0, 'gas_ocgt': 109.0, 'gas_recip': 0.0, 'gas_steam': 61.0, 'gas_wcmg': 56.31, 'hydro': 2967.0, 'pumps': 382.8, 'solar_utility': 195.6, 'solar_rooftop': 2151.0, 'wind': 3766.0, 'battery_discharging': 84.73, 'battery_charging': -0.48, 'exports': 0, 'imports': 0, 'price': 124.7, 'demand': 8621.0, 'generation': 26034.61, 'temperature': 0, 'fossilfuel': 16932.21, 'renewables': 9102.4, 'flow_NSW': 0, 'flow_QLD': 0, 'flow_SA': 0, 'flow_TAS': 0, 'flow_VIC': 0, 'last_update': datetime.datetime(2023, 7, 29, 7, 35, 39, tzinfo=datetime.timezone.utc), 'state': 26034.61, 'genvsdemand': 17413.61}
2023-07-29 17:36:27.521 DEBUG (MainThread) [custom_components.opennem] OpenNEM [au1] Region Attrs: ['demand', 'battery_charging', 'battery_discharging', 'bioenergy_biogas', 'bioenergy_biomass', 'coal_black', 'coal_brown', 'distillate', 'gas_ccgt', 'gas_ocgt', 'gas_recip', 'gas_steam', 'gas_wcmg', 'hydro', 'pumps', 'solar_rooftop', 'solar_utility', 'wind', 'price', 'fossilfuel', 'renewables', 'generation', 'genvsdemand', 'last_update']
2023-07-29 17:36:27.522 DEBUG (MainThread) [custom_components.opennem] OpenNEM [au1]: Values to pass to Sensor: {'bioenergy_biomass': 11.7, 'bioenergy_biogas': 11.1, 'coal_black': 10911.0, 'coal_brown': 4302.0, 'distillate': -0.1, 'gas_ccgt': 1493.0, 'gas_ocgt': 109.0, 'gas_recip': 0.0, 'gas_steam': 61.0, 'gas_wcmg': 56.31, 'hydro': 2967.0, 'pumps': 382.8, 'solar_utility': 195.6, 'solar_rooftop': 2151.0, 'wind': 3766.0, 'battery_discharging': 84.73, 'battery_charging': -0.48, 'price': 124.7, 'demand': 8621.0, 'generation': 26034.61, 'fossilfuel': 16932.21, 'renewables': 9102.4, 'last_update': datetime.datetime(2023, 7, 29, 7, 35, 39, tzinfo=datetime.timezone.utc), 'genvsdemand': 17413.61}
2023-07-29 17:36:27.522 DEBUG (MainThread) [custom_components.opennem] OpenNEM [au1]: Temp - {'bioenergy_biomass': 0, 'bioenergy_biogas': 0, 'coal_black': 0, 'coal_brown': 0, 'distillate': 0, 'gas_ccgt': 0, 'gas_ocgt': 0, 'gas_recip': 0, 'gas_steam': 0, 'gas_wcmg': 0, 'hydro': 0, 'pumps': 0, 'solar_utility': 0, 'solar_rooftop': 0, 'wind': 0, 'battery_discharging': 0, 'battery_charging': 0, 'exports': 0, 'imports': 0, 'price': 0, 'demand': 0, 'generation': 0, 'temperature': 0, 'fossilfuel': 0, 'renewables': 0, 'flow_NSW': 0, 'flow_QLD': 0, 'flow_SA': 0, 'flow_TAS': 0, 'flow_VIC': 0, 'last_update': None}
2023-07-29 17:36:27.522 DEBUG (MainThread) [custom_components.opennem] OpenNEM [au1]: Values After - {'bioenergy_biomass': 0, 'bioenergy_biogas': 0, 'coal_black': 0, 'coal_brown': 0, 'distillate': 0, 'gas_ccgt': 0, 'gas_ocgt': 0, 'gas_recip': 0, 'gas_steam': 0, 'gas_wcmg': 0, 'hydro': 0, 'pumps': 0, 'solar_utility': 0, 'solar_rooftop': 0, 'wind': 0, 'battery_discharging': 0, 'battery_charging': 0, 'exports': 0, 'imports': 0, 'price': 0, 'demand': 0, 'generation': 0, 'temperature': 0, 'fossilfuel': 0, 'renewables': 0, 'flow_NSW': 0, 'flow_QLD': 0, 'flow_SA': 0, 'flow_TAS': 0, 'flow_VIC': 0, 'last_update': None}
2023-07-29 17:36:27.525 DEBUG (MainThread) [custom_components.opennem] Finished fetching opennem data in 0.396 seconds (success: True)
2023-07-29 17:36:27.526 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform opennem
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'default_mode'
2023-07-29 17:36:27.532 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up opennem platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 370, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'default_mode'
```

**Comment by bacco007** [comment]
Hmm bugger - not sure when I'm going to get a chance to have a look either

**Comment by purcell-lab** [comment]
This issue seems to be around the **default_mode** argument here:
https://github.com/bacco007/sensor.opennem/blame/a8e3e987e4ded27ae20ec2f6ec2d5efcd2a641ae/custom_components/opennem/sensor.py#L64

Which isn't allowed in a **DeviceRegistry** call:
https://dev-docs.home-assistant.io/en/dev/api/helpers.html#homeassistant.helpers.device_registry.DeviceRegistry

I am unsure what this is trying to achieve, but deleting L64 seems to have brought the integration back to life, but I am unsure about other potential side effects.

**Comment by bacco007** [comment]
I've made the change in my setup and I'll run it for a few days to see what the impacts are

**Comment by Ralphy140** [comment]
Broken for me as well, Do we know if we will see up update to resolve ?

**Comment by tkrull75** [comment]
Just FYI - I have removed L64 and it has been working fine for me so far.

**Comment by purcell-lab** [comment]
Just upgraded to HA 2023.9 beta and the problems compound.

```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:621
Integration: Sensor (documentation, issues)
First occurred: 3:59:19 PM (5 occurrences)
Last logged: 3:59:20 PM

opennem: Not adding entity with invalid device info: Invalid device info {'configuration_url': 'https://opennem.org.au/', 'default_name': 'OpenNEM AU', 'entry_type': <DeviceEntryType.SERVICE: 'service'>, 'identifiers': {('opennem', 'a7ee906f3b8d7aec3092671872d4b716')}, 'manufacturer': 'OpenNEM', 'model': 'AU', 'name': 'OpenNEM AU'} for 'opennem' config entry: device info needs to either describe a device, link to existing device or provide extra information.
opennem: Not adding entity with invalid device info: Invalid device info {'configuration_url': 'https://opennem.org.au/', 'default_name': 'OpenNEM NSW', 'entry_type': <DeviceEntryType.SERVICE: 'service'>, 'identifiers': {('opennem', 'a6530deacb28acd41c69b6bdee087f11')}, 'manufacturer': 'OpenNEM', 'model': 'NSW', 'name': 'OpenNEM NSW'} for 'opennem' config entry: device info needs to either describe a device, link to existing device or provide extra information.
opennem: Not adding entity with invalid device info: Invalid device info {'configuration_url': 'https://opennem.org.au/', 'default_name': 'OpenNEM NEM', 'entry_type': <DeviceEntryType.SERVICE: 'service'>, 'identifiers': {('opennem', 'bd873550f63738f793cff632dd953fc8')}, 'manufacturer': 'OpenNEM', 'model': 'NEM', 'name': 'OpenNEM NEM'} for 'opennem' config entry: device info needs to either describe a device, link to existing device or provide extra information.
opennem: Not adding entity with invalid device info: Invalid device info {'configuration_url': 'https://opennem.org.au/', 'default_name': 'OpenNEM SA', 'entry_type': <DeviceEntryType.SERVICE: 'service'>, 'identifiers': {('opennem', 'af278bf2ad16f99be4205756d81c45b1')}, 'manufacturer': 'OpenNEM', 'model': 'SA', 'name': 'OpenNEM SA'} for 'opennem' config entry: device info needs to either describe a device, link to existing device or provide extra information.
opennem: Not adding entity with invalid device info: Invalid device info {'configuration_url': 'https://opennem.org.au/', 'default_name': 'OpenNEM QLD', 'entry_type': <DeviceEntryType.SERVICE: 'service'>, 'identifiers': {('opennem', 'aa67ae4b2192771ddb23243808cbf298')}, 'manufacturer': 'OpenNEM', 'model': 'QLD', 'name': 'OpenNEM QLD'} for 'opennem' config entry: device info needs to either describe a device, link to existing device or provide extra information.
```

**Comment by hendy-ghub** [comment]
> Just upgraded to HA 2023.9 beta and the problems compound.
> 
> ```
> Logger: homeassistant.components.sensor
> Source: helpers/entity_platform.py:621
> Integration: Sensor (documentation, issues)
> First occurred: 3:59:19 PM (5 occurrences)
> Last logged: 3:59:20 PM
> 
> opennem: Not adding entity with invalid device info: Invalid device info {'configuration_url': 'https://opennem.org.au/', 'default_name': 'OpenNEM AU', 'entry_type': <DeviceEntryType.SERVICE: 'service'>, 'identifiers': {('opennem', 'a7ee906f3b8d7aec3092671872d4b716')}, 'manufacturer': 'OpenNEM', 'model': 'AU', 'name': 'OpenNEM AU'} for 'opennem' config entry: device info needs to either describe a device, link to existing device or provide extra information.
> opennem: Not adding entity with invalid device info: Invalid device info {'configuration_url': 'https://opennem.org.au/', 'default_name': 'OpenNEM NSW', 'entry_type': <DeviceEntryType.SERVICE: 'service'>, 'identifiers': {('opennem', 'a6530deacb28acd41c69b6bdee087f11')}, 'manufacturer': 'OpenNEM', 'model': 'NSW', 'name': 'OpenNEM NSW'} for 'opennem' config entry: device info needs to either describe a device, link to existing device or provide extra information.
> opennem: Not adding entity with invalid device info: Invalid device info {'configuration_url': 'https://opennem.org.au/', 'default_name': 'OpenNEM NEM', 'entry_type': <DeviceEntryType.SERVICE: 'service'>, 'identifiers': {('opennem', 'bd873550f63738f793cff632dd953fc8')}, 'manufacturer': 'OpenNEM', 'model': 'NEM', 'name': 'OpenNEM NEM'} for 'opennem' config entry: device info needs to either describe a device, link to existing device or provide extra information.
> opennem: Not adding entity with invalid device info: Invalid device info {'configuration_url': 'https://opennem.org.au/', 'default_name': 'OpenNEM SA', 'entry_type': <DeviceEntryType.SERVICE: 'service'>, 'identifiers': {('opennem', 'af278bf2ad16f99be4205756d81c45b1')}, 'manufacturer': 'OpenNEM', 'model': 'SA', 'name': 'OpenNEM SA'} for 'opennem' config entry: device info needs to either describe a device, link to existing device or provide extra information.
> opennem: Not adding entity with invalid device info: Invalid device info {'configuration_url': 'https://opennem.org.au/', 'default_name': 'OpenNEM QLD', 'entry_type': <DeviceEntryType.SERVICE: 'service'>, 'identifiers': {('opennem', 'aa67ae4b2192771ddb23243808cbf298')}, 'manufacturer': 'OpenNEM', 'model': 'QLD', 'name': 'OpenNEM QLD'} for 'opennem' config entry: device info needs to either describe a device, link to existing device or provide extra information.
> ```

I deleted L63 default_name and it started working again

https://github.com/bacco007/sensor.opennem/blame/a8e3e987e4ded27ae20ec2f6ec2d5efcd2a641ae/custom_components/opennem/sensor.py#L63

**Comment by bacco007** [comment]
I've published a release with both changes - https://github.com/bacco007/sensor.opennem/releases/tag/2023.09.1

**Comment by purcell-lab** [comment]
Thanks that has reduced the breaking charges with .8 & .9 for me.

**Comment by purcell-lab** [comment]
Thanks that has reduced the breaking charges with .8 & .9 for me.
